title: vanilla-project.guide
description: >
  How do I start a project in a new language?
baseurl: ""
url: "https://vanilla-project.guide"

google_analytics: UA-101858487-1

port: 8080
host: 0.0.0.0
show_dir_listing: false

markdown: kramdown
plugins:
  - jekyll-feed
  - github-pages
exclude:
  - heroku
  - vendor
  - contributing.md
  - Gemfile
  - Gemfile.lock
  - template.md

permalink: pretty

collections:
  guides:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: page
  - scope:
      path: "_guides/ruby"
    values:
      language: Ruby
      icon: ruby.png
      paradigms:
        - object-oriented
        - dynamically-typed
      color: "#701516"
  - scope:
      path: "_guides/node"
    values:
      language: JavaScript
      icon: "js.png"
      paradigms:
        - object-oriented
        - dynamically-typed
      color: "#f1e05a"
  - scope:
      path: "_guides/php"
    values:
      language: PHP
      icon: "php.png"
      paradigms:
        - object-oriented
        - dynamically-typed
      color: "#4F5D95"
  - scope:
      path: "_guides/java"
    values:
      language: Java
      icon: "java.png"
      paradigms:
        - object-oriented
        - statically-typed
      color: "#F89820"

